fixed latest action to accept alpha, beta, rc, and latest

diff --git a/.github/workflows/publish-latest.yml b/.github/workflows/publish-latest.yml
--- a/.github/workflows/publish-latest.yml
+++ b/.github/workflows/publish-latest.yml
@@ -25,6 +25,23 @@ jobs:
         echo "::set-env name=VERSION::$VERSION"
         echo "::set-env name=TAG::$(echo "v${SHORT}-latest")"
 
+    - name: Set up JDK 11
+      uses: actions/setup-java@v1
+      with:
+        java-version: 11
+
+    - name: Test with ant
+      run: |
+         ant -noinput -buildfile build.xml run_tests
+         fails=$(grep -L  "Failures: 0, Errors: 0" test/junit/TEST-*)
+         if [ -n "$fails" ]; then
+           echo Errors in $fails
+           cat $fails
+           exit 1
+         fi
+      # do not exit before all commands are executed
+      shell: bash --noprofile --norc -o pipefail {0}
+
     - name: Sanity check
       run: |
         # tag is v1.2-latest
@@ -35,8 +52,8 @@ jobs:
           exit 1
         fi
 
-        # version is 1.2[.3]-567.latest
-        if [[ "${VERSION}" =~ ^[0-9][0-9]*[.][0-9][0-9]*([.][0-9][0-9]*)?-[0-9][0-9]*[.]latest$ ]]; then
+        # version is 1.2[.3]-567.latest,alpha, or beta
+        if [[ "${VERSION}" =~ ^[0-9][0-9]*[.][0-9][0-9]*([.][0-9][0-9]*)?-[0-9][0-9]*[.](latest|alpha|beta|rc)$ ]]; then
           echo version $VERSION okay
         else
           echo "version $VERSION not okay!"
@@ -64,24 +81,7 @@ jobs:
           fi
         else
           echo "Warning, previous build not found for ${TAG}!"
-        fi
-
-    - name: Set up JDK 11
-      uses: actions/setup-java@v1
-      with:
-        java-version: 11
-
-    - name: Test with ant
-      run: |
-         ant -noinput -buildfile build.xml run_tests
-         fails=$(grep -L  "Failures: 0, Errors: 0" test/junit/TEST-*)
-         if [ -n "$fails" ]; then
-           echo Errors in $fails
-           cat $fails
-           exit 1
-         fi
-      # do not exit before all commands are executed
-      shell: bash --noprofile --norc -o pipefail {0}
+        fi3597329be019bd66bf0e44762f74611acec08184
 
     - name: Build with ant
       run: ant -noinput -buildfile build.xml
@@ -105,6 +105,20 @@ jobs:
         REMOTE="https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
         git push --force "$REMOTE" "${TAG}"
 
+    - name: prepare meta
+      run: |
+        set -x
+        if [[ "${{ env.TAG }}" =~ .*-([0-9]*[.])?\([a-zA-Z][a-zA-Z]*\).* ]]; then
+          TYPE=$(echo ${{ env.TAG }} | sed -e "s/.*-\([0-9]*[.]\)\([a-zA-Z][a-zA-Z]*\).*/\2/")
+        else
+          TYPE=stable
+        fi
+        if [[ ! "$TYPE" =~ ^[a-zA-Z]+$ ]]; then
+          echo "invalid type $TYPE"
+          exit 1
+        fi
+        echo "::set-env name=TYPE::$TYPE"
+
     - name: Create release
       uses: meeDamian/github-release@2.0
       with:
@@ -125,20 +139,6 @@ jobs:
           magellan_v${{ env.VERSION }}.jar
           magellan_v${{ env.VERSION }}.zip
 
-    - name: prepare meta
-      run: |
-        set -x
-        if [[ "${{ env.TAG }}" =~ .*-[0-9.]*\([a-zA-Z][a-zA-Z]*\).* ]]; then
-          TYPE=$(echo ${{ env.TAG }} | sed -e "s/.*-[0-9.]*\([a-zA-Z][a-zA-Z]*\).*/\1/")
-        else
-          TYPE=stable
-        fi
-        if [[ ! "$TYPE" =~ ^[a-zA-Z]+$ ]]; then
-          echo "invalid type $TYPE"
-          exit 1
-        fi
-        echo "::set-env name=TYPE::$TYPE"
-
     - name: trigger meta action
       run: |
         curl -X POST https://api.github.com/repos/${{ github.repository_owner }}/magellan2.github.io/dispatches \
@@ -154,3 +154,4 @@ jobs:
               "tag" : "${{ env.TAG }}",
               "version" : "${{ env.VERSION }}",
               "type": "${{ env.TYPE }}" }}'
+
diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -95,6 +95,20 @@ jobs:
         value=$(json_escape "$value")
         echo "::set-env name=BODY::$value"
 
+    - name: prepare meta
+      run: |
+        set -x
+        if [[ "${{ env.TAG }}" =~ .*-([0-9]*[.])?\([a-zA-Z][a-zA-Z]*\).* ]]; then
+          TYPE=$(echo ${{ env.TAG }} | sed -e "s/.*-\([0-9]*[.]\)\([a-zA-Z][a-zA-Z]*\).*/\2/")
+        else
+          TYPE=stable
+        fi
+        if [[ ! "$TYPE" =~ ^[a-zA-Z]+$ ]]; then
+          echo "invalid type $TYPE"
+          exit 1
+        fi
+        echo "::set-env name=TYPE::$TYPE"
+
     - name: Create release
       uses: meeDamian/github-release@2.0
       with:
@@ -104,7 +118,7 @@ jobs:
         token: ${{ secrets.GITHUB_TOKEN }}
         commitish: master
         tag: ${{ env.TAG }}
-        name: Stable Release v${{ env.VERSION }}
+        name: Release v${{ env.VERSION }} (${{ env.TYPE }})
         body: ${{ env.BODY }}
         gzip: folders
         files: >
@@ -115,20 +129,6 @@ jobs:
           VERSION
           magellan_v${{ env.VERSION }}.jar
           magellan_v${{ env.VERSION }}.zip
-
-    - name: prepare
-      run: |
-        set -x
-        if [[ "${{ env.TAG }}" =~ .*-[0-9.]*\([a-zA-Z][a-zA-Z]*\).* ]]; then
-          TYPE=$(echo ${{ env.TAG }} | sed -e "s/.*-[0-9.]*\([a-zA-Z][a-zA-Z]*\).*/\1/")
-        else
-          TYPE=stable
-        fi
-        if [[ ! "$TYPE" =~ ^[a-zA-Z]+$ ]]; then
-          echo "invalid type $TYPE"
-          exit 1
-        fi
-        echo "::set-env name=TYPE::$TYPE"
 
 #    - name: trigger meta action
 #      run: |
@@ -143,4 +143,6 @@ jobs:
 #              "caller_repository" : "${{ github.repository }}",
 #              "meta_repository" : "${{ github.repository_owner }}/magellan-meta",
 #              "tag" : "${{ env.TAG }}",
+#              "version" : "${{ env.VERSION }}",
 #              "type": "${{ env.TYPE }}" }}'
+
