added versioned release action

diff --git a/.github/workflows/publish-latest.yml b/.github/workflows/publish-latest.yml
--- a/.github/workflows/publish-latest.yml
+++ b/.github/workflows/publish-latest.yml
@@ -4,7 +4,7 @@ name: Create pre-release
 on:
   push:
     branches:
-      - "master"
+      - "build-release"
 
 jobs:
   build:
@@ -13,6 +13,58 @@ jobs:
 
     steps:
     - uses: actions/checkout@v1
+
+    - name: Generate version string
+      id: get-version
+      run: |
+        VERSION=$(ant -q -S print_version)
+        SHORT=$(echo "${VERSION}" | cut -d. -f-2)
+        BUILD=$(cat .build.number | grep build.number | cut -f2 -d"=")
+        echo "::set-env name=BUILD::$BUILD"
+        echo "::set-env name=SHORT::$SHORT"
+        echo "::set-env name=VERSION::$VERSION"
+        echo "::set-env name=TAG::$(echo "v${SHORT}-latest")"
+
+    - name: Sanity check
+      run: |
+        # tag is v1.2-latest
+        if [[ "${TAG}" =~ ^v[0-9][0-9]*[.][0-9][0-9]*-latest$ ]]; then
+          echo tag $TAG okay
+        else
+          echo "tag (${VERSION}, ${SHORT}) $TAG not okay!"
+          exit 1
+        fi
+
+        # version is 1.2[.3]-latest.567
+        if [[ "${VERSION}" =~ ^[0-9][0-9]*[.][0-9][0-9]*([.][0-9][0-9]*)?-latest.[0-9][0-9]*$ ]]; then
+          echo version $VERSION okay
+        else
+          echo "version $VERSION not okay!"
+          exit 1
+        fi
+
+	# most recent tag has older build number
+        LASTTAG=$(git tag -l v* --sort='-committerdate' | head -1)
+        OLDBUILD=$(git show ${LASTTAG}:.build.number | grep build.number | cut -f2 -d"=")
+        if [[ "$OLDBUILD" =~ ^[0-9][0-9]*$ ]]; then
+          if (( BUILD == OLDBUILD )); then
+            echo "build.number $BUILD has not changed since most recent tag ${LASTTAG}, please update by running ant build locally!"
+            exit 1
+          fi
+        else
+          echo "bad tag or build $LASTTAG - $OLDBUILD"
+        fi
+
+        # last -latest tag has older build number
+        OLDBUILD=$(git show ${TAG}:.build.number | grep build.number | cut -f2 -d"=")
+        if [[ "$OLDBUILD" =~ ^[0-9][0-9]*$ ]]; then
+          if (( BUILD <= OLDBUILD )); then
+            echo "build.number $BUILD has not changed for tag ${TAG}, please update by running ant build locally!"
+            exit 1
+          fi
+        else
+          echo "Warning, previous build not found for ${TAG}!"
+        fi
 
     - name: Set up JDK 11
       uses: actions/setup-java@v1
@@ -34,28 +86,10 @@ jobs:
     - name: Build with ant
       run: ant -noinput -buildfile build.xml
 
-    - name: Generate version string
-      id: get-version
-      run: |
-        VERSION=$(ant -q -S print_version)
-        echo "::set-env name=BASE::${VERSION}"
-        echo "::set-env name=SHORT::$(echo "${BASE}" | cut -d. -f-2)"
-        echo "::set-env name=VERSION::${VERSION}-latest"
-        echo "::set-env name=TAG::v${SHORT}-latest"
-      
-    - name: Sanity check
-      run: |
-        if [[ "$TAG" =~ ^v[0-9][0-9]*[.][0-9][0-9]*([.][0-9][0-9]*)*-latest$ ]]; then
-          echo version $BASE okay
-        else
-          echo version $BASE not okay!
-          exit 1
-        fi
-
     - name: Read RELEASENOTES and CHANGELOG
       id: changelog
       run: |
-        value=$(cat RELEASENOTES.txt | iconv -f ISO-8859-1; echo -e '\n# Excerpt from CHANGELOG.txt\n\n'; head -20 CHANGELOG.txt | iconv -f ISO-8859-1; echo -e '\n...\n' )
+        value=$(cat doc/NIGHTLY.txt | iconv -f ISO-8859-1; echo -e '\n\n'; echo -e '\n# Excerpt from CHANGELOG.txt\n\n'; head -20 CHANGELOG.txt | iconv -f ISO-8859-1; echo -e '\n...\n' )
         json_escape () {
           printf '%s' "$1" | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))[1:-1]'
         }
@@ -79,7 +113,7 @@ jobs:
         token: ${{ secrets.GITHUB_TOKEN }}
         commitish: master
         tag: ${{ env.TAG }}
-        name: Pre-Release  ${{ env.VERSION }}
+        name: Pre-Release  v${{ env.VERSION }}
         body: ${{ env.BODY }}
         gzip: folders
         files: >
@@ -87,7 +121,6 @@ jobs:
           README.md
           RELEASENOTES.txt
           CHANGELOG.txt
-          magellan_v${{ env.BASE }}.zip
-          magellan_v${{ env.BASE }}.jar
-
+          magellan_v${{ env.VERSION }}.jar
+          magellan_v${{ env.VERSION }}.zip
 
