Release v2.1.0 (#51)
* fix: update several urls
* fix: update build path and docs and ignore some Unit test failures
* fix: update github action versions
* fix: remove unsupported set-env command, it's not really necessary
* fix: continue on error should never happen
* fix: test a different approach to retrieve secret
* fix: try to reanable izpack on Java11
* fix: clean upload of artifacts
* fix: update build pipeline
* fix: repair build process and clean up a bit #49, #50
* fix: CHANGELOG for PR ttps://github.com/magellan2/magellan2/pull/48
* fix: add IZPack Installer file again to Release Notes
* chore: test if we can trigger a worflow on the homepage repo
* fix: update update path for install4j
* fix: hopefully last commit before release

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,5 +1,4 @@
-name: Create pre-release
-# Test, build, and publish a release and tag it with "version-latest" on pushes to master
+name: "Run tests, build artifacts, publish on default branch"
 
 on:
   push:
@@ -8,33 +7,37 @@ on:
 
 jobs:
   build:
-    name: Create pre-release
+    name: "Test, Build and Create pre-release"
     runs-on: ubuntu-latest
+    env:
+      INSTALL4J_KEY: ${{ secrets.INSTALL4J_LICENSE_KEY_1 }}
+    continue-on-error: false
 
     steps:
-    - uses: actions/checkout@v3
+    - name: "Checkout repository"
+      uses: actions/checkout@v4
       with:
         fetch-tags: true
         fetch-depth: 0
 
-    - name: Generate version string
+    - name: "Generate version string"
       id: get-version
       run: |
         VERSION=$(ant -q -S print_version)
         SHORT=$(echo "${VERSION}" | cut -d. -f-2)
         BUILD=$(cat .build.number | grep build.number | cut -f2 -d"=")
-        echo "BUILD=$BUILD" >> $GITHUB_OUTPUT
-        echo "SHORT=$SHORT" >> $GITHUB_OUTPUT
-        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
-        echo "TAG=$(echo "v${SHORT}-latest")" >> $GITHUB_OUTPUT
+        echo "BUILD=${BUILD}" >> $GITHUB_OUTPUT
+        echo "SHORT=${SHORT}" >> $GITHUB_OUTPUT
+        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
+        echo "TAG=v${VERSION}" >> $GITHUB_OUTPUT
 
-    - name: Set up JDK 11
+    - name: "Set up JDK 11"
       uses: actions/setup-java@v3
       with:
-        java-version: 11
         distribution: 'temurin'
+        java-version: 11
 
-    - name: Sanity check
+    - name: "Sanity check"
       id: sanity_check
       run: |
         # env
@@ -42,19 +45,20 @@ jobs:
         SHORT=${{ steps.get-version.outputs.SHORT }}
         VERSION=${{ steps.get-version.outputs.VERSION }}
         TAG=${{ steps.get-version.outputs.TAG }}
-        # tag is v1.2-latest
-        if [[ "${TAG}" =~ ^v[0-9][0-9]*[.][0-9][0-9]*-latest$ ]]; then
-          echo tag $TAG okay
+
+        # version is v1.2.3
+        if [[ "${VERSION}" =~ ^[0-9][0-9]*[.][0-9][0-9]*[.][0-9][0-9]*$ ]]; then
+          echo "Version $VERSION is okay"
         else
-          echo "tag (${VERSION}, ${SHORT}) $TAG not okay!"
+          echo "Version format $VERSION is not okay!"
           exit 1
         fi
 
-        # version is 1.2[.3]-567.latest,alpha, or beta
-        if [[ "${VERSION}" =~ ^[0-9][0-9]*[.][0-9][0-9]*([.][0-9][0-9]*)?-[0-9][0-9]*[.](latest|alpha|beta|rc)$ ]]; then
-          echo version $VERSION okay
+        # tag is v1.2.3
+        if [[ "${TAG}" =~ ^v[0-9][0-9]*[.][0-9][0-9]*[.][0-9][0-9]*$ ]]; then
+          echo "Tag $TAG okay"
         else
-          echo "version $VERSION not okay!"
+          echo "Tag $TAG is not okay for version $VERSION!"
           exit 1
         fi
 
@@ -70,23 +74,12 @@ jobs:
           echo "bad tag or build $LASTTAG - $OLDBUILD"
         fi
 
-        # last -latest tag has older build number
-        OLDBUILD=$(git show ${TAG}:.build.number | grep build.number | cut -f2 -d"=")
-        if [[ "$OLDBUILD" =~ ^[0-9][0-9]*$ ]]; then
-          if (( BUILD <= OLDBUILD )); then
-            echo "build.number $BUILD has not changed for tag ${TAG}, please update by running ant build locally!"
-            exit 1
-          fi
-        else
-          echo "Warning, previous build not found for ${TAG}!"
-        fi
-
-    - name: Test with ant
+    - name: "Test with ant"
       run: |
          ant -noinput -buildfile build.xml run_tests
          fails=$(grep -L  "Failures: 0, Errors: 0" test/junit/TEST-*)
          if [ -n "$fails" ]; then
-           echo Errors in $fails
+           echo "Errors in $fails"
            cat $fails
            exit 1
          fi
@@ -98,22 +91,41 @@ jobs:
       # do not exit before all commands are executed
       shell: bash --noprofile --norc -o pipefail {0}
 
-    - name: Build with ant
-      env:
-        INSTALL4J_KEY: ${{secrets.INSTALL4J_LICENSE_KEY_1}}
+    - name: "Build izpack with ant"
       run: |
-        ant -noinput -buildfile build.xml distribute_install4j
+        ant -noinput -buildfile build.xml distribute
 
-    - name: Read RELEASENOTES and CHANGELOG
+    - name: "Upload izpack binary artifacts"
+      uses: actions/upload-artifact@v4
+      with:
+        name: binaries.izpack
+        path: |
+          magellan_v*.jar
+          magellan_v*.zip
+
+    - name: "Build install4j with ant"
+      run: ant -noinput -buildfile build.xml
+
+    - name: "Upload install4j binary artifacts"
+      uses: actions/upload-artifact@v4
+      with:
+        name: binaries.install4j
+        path: |
+          Magellan_installer_*.exe
+          Magellan_installer_*.sh
+          Magellan_installer_*.dmg
+
+    - name: "Read RELEASENOTES and CHANGELOG"
       id: changelog
       run: |
-        value=$(cat doc/NIGHTLY.txt | iconv -f ISO-8859-1; echo -e '\n\n'; echo -e '\n## Excerpt from CHANGELOG.txt\n\n'; head -20 CHANGELOG.txt | iconv -f ISO-8859-1; echo -e '\n...\n' )
-        value="${value//'%'/'%25'}"
-        value="${value//$'\n'/'%0A'}"
-        value="${value//$'\r'/'%0D'}"
-        echo "BODY=$value" >> $GITHUB_OUTPUT
+        cat RELEASENOTES.txt | iconv -f ISO-8859-1 > RELEASE.md
+        echo '' >> RELEASE.md
+        echo '## Excerpt from CHANGELOG' >> RELEASE.md
+        echo '' >> RELEASE.md
+        head -20 CHANGELOG.txt | iconv -f ISO-8859-1 >> RELEASE.md
+        echo '...' >> RELEASE.md
 
-    - name: Publish git tag "vX.Y-latest"
+    - name: "Publish git tag vX.Y.Z"
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
@@ -121,35 +133,20 @@ jobs:
         git config user.name "$GITHUB_ACTOR"
         git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
         git remote -v
-        # should we delete the old release and assets?
-        # gh release delete ${TAG} -y || echo "continuing ..."
+        gh release delete ${TAG} -y || echo "continuing ..."
         git tag -f "${TAG}"
         REMOTE="https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
         git push --force "$REMOTE" "${TAG}"
 
-    - name: prepare meta
-      id: prepare-meta
-      run: |
-        set -x
-        if [[ "${{ steps.get-version.outputs.TAG }}" =~ .*-([0-9]*[.])?([a-zA-Z][a-zA-Z]*).* ]]; then
-          TYPE=$(echo ${{ steps.get-version.outputs.TAG }} | sed -e "s/.*-\([0-9]*[.]\)\?\([a-zA-Z][a-zA-Z]*\).*/\2/")
-        else
-          TYPE=stable
-        fi
-        if [[ ! "$TYPE" =~ ^[a-zA-Z]+$ ]]; then
-          echo "invalid type $TYPE"
-          exit 1
-        fi
-        echo "TYPE=$TYPE" >> $GITHUB_OUTPUT
-
-    - name: Release
-      uses: softprops/action-gh-release@v1
+    - name: "Create Release"
+      uses: softprops/action-gh-release@v2
       with:
         target_commitish: master
         tag_name: ${{ steps.get-version.outputs.TAG }}
-        prerelease: true
-        name: Pre-Release v${{ steps.get-version.outputs.VERSION }} (${{ steps.prepare-meta.outputs.TYPE }})
-        body: ${{ steps.changelog.outputs.BODY }}
+        draft: true
+        prerelease: false
+        name: ${{ steps.get-version.outputs.TAG }}
+        body_path: RELEASE.md
         files: |
           LICENSE.txt
           README.md
@@ -158,11 +155,12 @@ jobs:
           VERSION
           installer/install4j/updates.xml
           magellan_v${{ steps.get-version.outputs.VERSION }}.zip
+          magellan_v${{ steps.get-version.outputs.VERSION }}.jar
           Magellan_installer_windows-x64_v${{ steps.get-version.outputs.VERSION }}.exe
           Magellan_installer_unix_v${{ steps.get-version.outputs.VERSION }}.sh
           Magellan_installer_macos_v${{ steps.get-version.outputs.VERSION }}.dmg
 
-    - name: trigger meta action
+    - name: "Trigger meta action to inform homepage"
       run: |
         curl -sS -o meta.log \
           -X POST https://api.github.com/repos/${{ github.repository_owner }}/magellan2.github.io/dispatches \
@@ -177,7 +175,8 @@ jobs:
               "meta_repository": "${{ github.repository_owner }}/magellan2.github.io",
               "tag": "${{ steps.get-version.outputs.TAG }}",
               "version": "${{ steps.get-version.outputs.VERSION }}",
-              "type": "${{ steps.prepare-meta.outputs.TYPE }}" }}'
+              "build": "${{ steps.get-version.outputs.BUILD }}",
+              "type": "stable" }}'
         if [ -s meta.log ]; then
           cat meta.log
           rm meta.log
